SET SCHEMA MUSEU

DROP TABLE OBRADEARTE

CREATE TABLE OBRADEARTE (
	ID INTEGER not null primary key,
	TITULO VARCHAR(20) not null,
	ARTISTA VARCHAR(20) not null,
	MATERIAL VARCHAR(20) not null,
	ANO INTEGER not null,
	CATEGORIA INTEGER not null,
	TIPO VARCHAR(20),
	ALTURA REAL
)

INSERT INTO OBRADEARTE (ID, TITULO, ARTISTA, MATERIAL, ANO, CATEGORIA, TIPO)
VALUES (1, 'Mona Lisa', 'Leonardo da Vinci', 'Madeira', 1503, 1, 'Óleo')

INSERT INTO OBRADEARTE (ID, TITULO, ARTISTA, MATERIAL, ANO, CATEGORIA, ALTURA)
VALUES (2, 'David', 'Michelangelo', 'Mármore', 1501, 2, 4.10)

INSERT INTO OBRADEARTE (ID, TITULO, ARTISTA, MATERIAL, ANO, CATEGORIA, TIPO)
VALUES (3, 'O Lavrador de Café', 'Cândido Portinari', 'Madeira', 1939, 1, 'Óleo')

INSERT INTO OBRADEARTE (ID, TITULO, ARTISTA, MATERIAL, ANO, CATEGORIA, ALTURA)
VALUES (4, 'O Pensador', 'Auguste Rodin', 'Bronze', 1909, 2, 1.40)